version: '3'
services:
  db:
    image: mysql:8 # on 2018-04-07, this is an "RC" release; required for UUID sanity
    env_file:
      - ./schema/mysql.env
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./schema:/schema
      - ./schema/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306" # host:container (edit the 'host' one if you like)
  web:
    image: nginx:alpine
    depends_on:
        - db
        - php
    ports:
        - "8816:80" # host:container
    volumes:
        - ./php:/app
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php # This "dot" means "./Dockerfile"
    volumes:
        - ./php:/app
    depends_on:
      - db
